export const ACTION_TYPE = {
   ADMIN_SIGN_IN: "ADMIN_SIGN_IN",
   SET_LOGIN_USER: "SET_LOGIN_USER",
   REMOVE_USER: "REMOVE_USER",
   USER_LOGIN_LODING: "USER_LOGIN_LODING",
   PRODUCT_CATEGORY_INSERT: "PRODUCT_CATEGORY_INSERT",
   PRODUCT_CATEGORY_LOADING: "PRODUCT_CATEGORY_LOADING",
   REMOVE_PRODUCT_CATEGORY_INFO: "REMOVE_PRODUCT_CATEGORY_INFO",
   FETCH_PRODUCTS_CATEGORYS: "FETCH_PRODUCTS_CATEGORYS",
   INSERT_NEW_CATEGORY: "INSERT_NEW_CATEGORY",
   EDIT_CATEGORY: "EDIT_CATEGORY",
   SELECTED_EDIT_CATEGORY: "SELECTED_EDIT_CATEGORY",
};
