export const AUTH_ACTION_TYPE = {
   SIGN_IN_USERS: 'SIGN_IN_USERS',
   SIGN_IN_USERS_LOADING: 'SIGN_IN_USERS_LOADING',
   ADMIN_SIGN_IN: 'ADMIN_SIGN_IN',
   SET_LOGIN_USER: 'SET_LOGIN_USER',
   REMOVE_USER: 'REMOVE_USER',
   USER_LOGIN_LODING: 'USER_LOGIN_LODING',
};
