export const INDEX_ACTION_TYPE = {
   SHOW_AND_HIDE_CART_SIDEBAR: 'SHOW_AND_HIDE_CART_SIDEBAR',
   GET_TRANDING_PRODUCTS: 'GET_TRANDING_PRODUCTS',
   GET_TRANDING_PRODUCTS_ERROR: 'GET_TRANDING_PRODUCTS_ERROR',
   GET_TRANDING_PRODUCTS_LOADING: 'GET_TRANDING_PRODUCTS_LOADING',
};
